# Generated by Django 3.1.7 on 2021-03-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Емейл')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('massage', models.TextField(blank=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение, заказ',
                'verbose_name_plural': 'Сообщения, заказы',
            },
        ),
    ]
