# Generated by Django 3.1.7 on 2021-03-27 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sphere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Вид деятельности')),
            ],
            options={
                'verbose_name': 'Вид деятельности',
                'verbose_name_plural': 'Виды деятельности',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(blank=True, max_length=120, verbose_name='Краткое описание')),
                ('long_description', models.CharField(blank=True, max_length=790, verbose_name='Полное описание')),
                ('slogan', models.CharField(blank=True, max_length=30, verbose_name='Слоган после заголовка')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Фото')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yard.sphere')),
            ],
        ),
    ]
