# Generated by Django 3.1.7 on 2021-03-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0002_service_sphere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя, фамилия')),
                ('testimonial', models.CharField(blank=True, max_length=800, verbose_name='Отзыв')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Фото человека')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Подробности о виде деятельности', 'verbose_name_plural': 'Подробности о видах деятельности'},
        ),
    ]
