# Generated by Django 3.1.7 on 2021-03-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0003_auto_20210329_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='anchor',
            field=models.CharField(blank=True, max_length=30, verbose_name='Анкор'),
        ),
        migrations.AlterField(
            model_name='service',
            name='long_description',
            field=models.CharField(blank=True, max_length=900, verbose_name='Полное описание'),
        ),
    ]
