# Generated by Django 3.1.7 on 2021-03-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0005_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='anchor',
        ),
        migrations.AddField(
            model_name='service',
            name='section_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='section id в шаблоне'),
        ),
    ]
