# Generated by Django 3.1.7 on 2021-03-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0006_auto_20210330_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='anchor',
            field=models.CharField(blank=True, max_length=30, verbose_name='Анкор'),
        ),
    ]
