# Generated by Django 3.1.7 on 2021-03-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0007_service_anchor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='section_id',
        ),
        migrations.AddField(
            model_name='service',
            name='service_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='service id в шаблоне'),
        ),
    ]
