# Generated by Django 3.1.7 on 2021-03-30 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0008_auto_20210330_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='anchor',
        ),
    ]
