# Generated by Django 3.1.7 on 2021-03-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0009_remove_service_anchor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sphere',
            name='prefix',
            field=models.CharField(blank=True, max_length=3, verbose_name='Префикс'),
        ),
    ]
