# Generated by Django 3.1.7 on 2021-03-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0010_sphere_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sphere',
            name='prefix',
            field=models.CharField(blank=True, max_length=4, verbose_name='Префикс'),
        ),
    ]
