# Generated by Django 3.1.7 on 2021-03-30 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0012_auto_20210330_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': ' Проект', 'verbose_name_plural': ' Проекты'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '  Подробно о виде деятельности', 'verbose_name_plural': '  Подробно о видах деятельности'},
        ),
        migrations.AlterModelOptions(
            name='sphere',
            options={'verbose_name': '   Вид деятельности', 'verbose_name_plural': '   Виды деятельности'},
        ),
    ]
