# Generated by Django 3.1.7 on 2022-02-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20220209_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetail',
            name='title_1',
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='text_1',
            field=models.CharField(blank=True, max_length=5000, verbose_name='Текст на Главной'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='text_2',
            field=models.CharField(blank=True, max_length=5000, verbose_name='Текст в разделе'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='title_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название текста в разделе'),
        ),
    ]
