# Generated by Django 3.1.7 on 2022-02-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20220209_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='banner',
            field=models.FileField(blank=True, upload_to='banners', verbose_name='Баннер в шапке 1600*235'),
        ),
    ]
